version: '3.8'

services:
  app:
    build: .
    container_name: mensageiro-orcamento-api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_PATH=/app/data/database.sqlite
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
